exp:
    name: ewc
    names_exp_delete: ['tmp', 'train_ewc']
    n_workers: 4
    idx_device: 0
    train:
        batch_size: 4
        n_epochs: [10, 240, 680, 64]
        optimizer:
            name: adam
            lr: 1e-4
    val:
        batch_size: 4
        n_iters_once: 5000
        skip_initial_val: True
    test:
        batch_size: 4

dataset:
    name: continual3d

model:
    name: continual_reg
    ws_loss:
        mi: 0.
        ncc: 1
        dice: 1.
        tre: 1.
        membrane: 1.
        bending: 1.
    ncc:
        win: 3

method:
    name: ewc_on
    ewc:
        e_lambda: 1e7
        gamma: 1
