exp:
    name: sgd
    names_exp_delete: ['tmp', 'train_sgd']
    n_workers: 2
    idx_device: 0
    train:
        batch_size: 4
        n_epochs: [10, 240, 680, 64]
        optimizer:
            name: adam
            lr: 1e-4
    val:
        batch_size: 4
        n_epochs_once: 10
        skip_initial_val: True
        no_val_before_epoch: 0
    test:
        batch_size: 4

dataset:
    name: continual3d

model:
    name: continual_reg
    ws_loss:
        mi: 0.
        ncc: 1
        dice: 1.
        tre: 1.
        membrane: 1.
        bending: 1.

method:
    name: sgd



